"""Adversarial integration tests for proxy / Host header hardening.

These tests pin the *behavioural* contract of the request pipeline configured
by ``app.main``. They bypass ``uvicorn``'s ``--proxy-headers`` flag entirely
and inject the ASGI scope directly so we can assert, with deterministic peer
IPs, Host headers and forwarded headers, that:

- A request whose immediate peer is **not** in ``TRUSTED_FORWARDED_PROXIES``
  cannot smuggle a different scheme/host/client IP via ``X-Forwarded-*`` or
  the RFC 7239 ``Forwarded`` header.
- A request whose immediate peer **is** trusted promotes exactly the
  forwarded headers to ``scope["scheme"]``, ``scope["server"]`` and
  ``scope["client"]`` — once and only once.
- The ``TrustedHost`` enforcer rejects unknown hosts with ``400`` and accepts
  the configured public hosts as well as the cloudflared-emitted ``Host``
  (``127.0.0.1:8000``) when explicitly listed.
- Redirects generated by ``StaticFiles(html=True)`` for ``/app`` and by the
  router for ``/api/v1/health/`` (trailing slash) preserve the public origin
  when the peer is trusted, and never leak an internal loopback origin to a
  hostile peer.
- HSTS is emitted only when the *external* scheme is HTTPS, never in
  development, and never carries ``includeSubDomains`` unless explicitly
  configured.
- ``/docs``, ``/redoc`` and ``/openapi.json`` are gated to ``development`` and
  never serve a schema outside that environment.

These tests are RED-first: the production ASGI middleware and the
configuration wiring do not yet exist, so they fail with
``ImportError``/``AttributeError``/``400``/``307`` until
``app.core.proxy`` exposes ``ProxyHeadersMiddleware`` /
``TrustedHostEnforcerMiddleware`` and ``app.main`` wires them. The assertions
below describe the *intended* contract and must all pass once the
implementation matches the spec.
"""
from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

import pytest

# ── Helpers ─────────────────────────────────────────────────────────────────


def _build_scope(
    *,
    path: str,
    peer: tuple[str, int],
    host_header: str,
    headers: list[tuple[bytes, bytes]] | None = None,
    scheme: str = "http",
) -> dict[str, Any]:
    """Build a minimal ASGI HTTP scope for direct invocation.

    Returns a scope dict compatible with Starlette's HTTPConnection. The
    ``headers`` list is augmented with a synthetic ``host`` header taken from
    ``host_header`` if not already present.
    """
    if headers is None:
        headers = []
    has_host = any(k.lower() == b"host" for k, _ in headers)
    if not has_host:
        headers = [*headers, (b"host", host_header.encode("latin-1"))]
    return {
        "type": "http",
        "asgi": {"version": "3.0", "spec_version": "2.3"},
        "http_version": "1.1",
        "method": "GET",
        "scheme": scheme,
        "path": path,
        "raw_path": path.encode("latin-1"),
        "query_string": b"",
        "headers": headers,
        "server": (host_header.partition(":")[0], int(host_header.rpartition(":")[2]) if ":" in host_header else 80),
        "client": peer,
        "root_path": "",
        "extensions": {},
    }


async def _invoke(scope: dict[str, Any]) -> tuple[int, list[tuple[bytes, bytes]], bytes]:
    """Invoke the ASGI app with ``scope`` and return ``(status, headers, body)``."""
    from app.main import app  # imported lazily so tests can monkeypatch settings first

    sent: list[dict[str, Any]] = []

    async def receive() -> dict[str, Any]:
        return {"type": "http.request", "body": b"", "more_body": False}

    async def send(message: dict[str, Any]) -> None:
        sent.append(message)

    # Strip query string that ASGITransport would otherwise attach.
    await app(scope, receive, send)

    start = next(m for m in sent if m["type"] == "http.response.start")
    body = b"".join(m.get("body", b"") for m in sent if m["type"] == "http.response.body")
    return start["status"], start.get("headers", []), body


# ── Settings isolation ──────────────────────────────────────────────────────


@pytest.fixture
def hardened_app(monkeypatch: pytest.MonkeyPatch) -> AsyncIterator[None]:
    """Configure settings for production-shaped adversarial scenarios.

    Production demands a non-empty TRUSTED_HOSTS, CORS_ORIGINS and
    TRUSTED_FORWARDED_PROXIES; the cloudflared peer in this environment is
    ``127.0.0.1:8000``. ``SECRET_KEY`` is a long random value so the
    validator does not reject it.
    """
    from app.core import config

    base_kwargs: dict[str, object] = {
        "ENVIRONMENT": "production",
        "SECRET_KEY": "x" * 64,
        "CORS_ORIGINS": ["https://markee.batata.cc"],
        "TRUSTED_HOSTS": [
            "markee.batata.cc",
            "app.markee.batata.cc",
            "127.0.0.1:8000",
        ],
        "TRUSTED_FORWARDED_PROXIES": ["127.0.0.1"],
        "ENABLE_MOCK_FALLBACK": False,
        "DB_CREATE_ALL_ON_STARTUP": False,
    }
    test_settings = config.Settings(**base_kwargs)  # type: ignore[arg-type]
    monkeypatch.setattr(config, "settings", test_settings)
    # Clear cached helpers that captured the original settings.
    monkeypatch.setattr(config, "get_settings", lambda: test_settings)
    yield


# ── Host spoofing ───────────────────────────────────────────────────────────


class TestHostSpoofing:
    """An unknown ``Host`` header must be rejected with 400."""

    @pytest.mark.asyncio
    async def test_untrusted_host_returns_400(self, hardened_app) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="evil.example.com",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 400

    @pytest.mark.asyncio
    async def test_trusted_loopback_host_passes(self, hardened_app) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 200

    @pytest.mark.asyncio
    async def test_trusted_public_host_passes(self, hardened_app) -> None:
        scope = _build_scope(
            path="/health",
            peer=("203.0.113.10", 51234),
            host_header="markee.batata.cc",
        )
        status, _headers, _body = await _invoke(scope)
        # Public peer is NOT trusted for forwarded headers but the Host itself
        # is in the allow-list, so the request reaches the router.
        assert status == 200

    @pytest.mark.asyncio
    async def test_loopback_with_arbitrary_port_returns_400(self, hardened_app) -> None:
        """Host: 127.0.0.1:6666 must NOT satisfy an allow-list with :8000."""
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:6666",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 400

    @pytest.mark.asyncio
    async def test_crlf_in_host_returns_400(self, hardened_app) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="markee.batata.cc\r\nX-Evil: 1",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 400


# ── Forwarded header gating ────────────────────────────────────────────────


class TestForwardedHeaderGating:
    """Forwarded headers are honoured only when the immediate peer is trusted."""

    @pytest.mark.asyncio
    async def test_untrusted_peer_cannot_inject_https_scheme(self, hardened_app) -> None:
        """A direct request from a non-trusted peer must not see HTTPS.

        The Health endpoint returns 200 regardless of scheme; we assert that
        ``scope["scheme"]`` seen by the router is ``http`` because the
        untrusted X-Forwarded-Proto=https is stripped.
        """
        scope = _build_scope(
            path="/health",
            peer=("203.0.113.10", 51234),
            host_header="markee.batata.cc",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 200
        # HSTS must NOT be present because the request came in as http.
        hsts = [v for k, v in _headers if k.lower() == b"strict-transport-security"]
        assert hsts == [], "HSTS must not be emitted on an untrusted-peer http request"

    @pytest.mark.asyncio
    async def test_untrusted_peer_cannot_inject_host(self, hardened_app) -> None:
        """A direct request cannot smuggle a different Host via X-Forwarded-Host."""
        scope = _build_scope(
            path="/health",
            peer=("203.0.113.10", 51234),
            host_header="markee.batata.cc",
            headers=[(b"x-forwarded-host", b"evil.example.com")],
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 200
        # If an attacker had successfully rewritten the Host, the trust check
        # above would have returned 400. We additionally verify the header is
        # not echoed back in any redirect Location.
        assert b"evil.example.com" not in _body

    @pytest.mark.asyncio
    async def test_untrusted_peer_cannot_inject_client_ip(self, hardened_app) -> None:
        """An untrusted X-Forwarded-For is never trusted as the client IP."""
        scope = _build_scope(
            path="/health",
            peer=("203.0.113.10", 51234),
            host_header="markee.batata.cc",
            headers=[(b"x-forwarded-for", b"192.0.2.1")],
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 200
        # No leakage of the spoofed IP into any response header.
        for k, v in _headers:
            assert v != b"192.0.2.1"

    @pytest.mark.asyncio
    async def test_trusted_peer_promotes_forwarded_scheme_to_https(
        self, hardened_app
    ) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="markee.batata.cc",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        status, headers, _body = await _invoke(scope)
        assert status == 200
        hsts = [v for k, v in headers if k.lower() == b"strict-transport-security"]
        assert hsts, "HSTS must be emitted when a trusted peer reports https"
        # includeSubDomains is opt-in; the default policy must not enable it.
        assert b"includeSubDomains" not in hsts[0]

    @pytest.mark.asyncio
    async def test_trusted_peer_promotes_forwarded_host(self, hardened_app) -> None:
        """When trusted, the Host seen by the router becomes the forwarded host."""
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",  # what cloudflared sends
            headers=[(b"x-forwarded-host", b"markee.batata.cc")],
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 200

    @pytest.mark.asyncio
    async def test_forwarded_header_not_applied_twice(self, hardened_app) -> None:
        """Double application would convert https→http via an XFP=https chain.

        Build a scope whose ``headers`` already include X-Forwarded-Proto and
        wrap it twice through the proxy middleware. After the first pass, the
        scheme is promoted; the second pass must not demote it because the
        X-Forwarded-Proto header is consumed exactly once.
        """
        # We test the single-pass behaviour here: the middleware reads
        # X-Forwarded-Proto from the scope and removes it; calling it twice
        # with the same scope would otherwise re-apply. The contract is that
        # the header is consumed in-place and absent on a second pass.
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        # First pass promotes scheme to https.
        await _invoke(scope)
        # After the middleware ran, the scope's scheme is https and the
        # x-forwarded-proto header is gone.
        assert scope["scheme"] == "https"
        assert all(k.lower() != b"x-forwarded-proto" for k, _ in scope["headers"])


# ── Redirect preservation ──────────────────────────────────────────────────


class TestRedirects:
    """StaticFiles redirects must use the external origin, not the loopback."""

    @pytest.mark.asyncio
    async def test_app_trailing_slash_redirect_uses_external_origin(
        self, hardened_app
    ) -> None:
        """GET /app should respond with 307 whose Location points to /app/.

        We do not assert the absolute host because Starlette may emit either
        a relative path or an absolute URL. We DO assert that the Location
        never leaks ``127.0.0.1`` or an unexpected host to a hostile peer.
        """
        scope = _build_scope(
            path="/app",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        status, headers, _body = await _invoke(scope)
        # StaticFiles(html=True) responds 307 to add the trailing slash.
        assert status in (200, 307)
        location = next(
            (v for k, v in headers if k.lower() == b"location"), b""
        )
        if status == 307:
            assert location.endswith(b"/app/") or location == b"/app/"
            assert b"127.0.0.1" not in location

    @pytest.mark.asyncio
    async def test_api_trailing_slash_redirect_preserves_host(
        self, hardened_app
    ) -> None:
        """GET /api/v1/health/ trailing slash redirect keeps the external host."""
        scope = _build_scope(
            path="/api/v1/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        status, headers, _body = await _invoke(scope)
        # FastAPI's redirect_slashes is on by default; we get 307 → /api/v1/health/
        # with Location path-relative or absolute-relative. Critical: the
        # redirect must not leak 127.0.0.1 to an external client.
        location = next(
            (v for k, v in headers if k.lower() == b"location"), b""
        )
        if status in (307, 308):
            assert b"127.0.0.1" not in location or b"127.0.0.1:8000" in location


# ── HSTS conditional ───────────────────────────────────────────────────────


class TestHSTS:
    """HSTS must reflect the external scheme only, never the local socket."""

    @pytest.mark.asyncio
    async def test_no_hsts_on_direct_http_request(self, hardened_app) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="markee.batata.cc",
            # No X-Forwarded-Proto: the local socket is http.
        )
        status, headers, _body = await _invoke(scope)
        assert status == 200
        hsts = [v for k, v in headers if k.lower() == b"strict-transport-security"]
        assert hsts == [], "HSTS must not be emitted over plain http"

    @pytest.mark.asyncio
    async def test_hsts_emitted_when_trusted_peer_reports_https(
        self, hardened_app
    ) -> None:
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
            headers=[(b"x-forwarded-proto", b"https")],
        )
        status, headers, _body = await _invoke(scope)
        assert status == 200
        hsts = [v for k, v in headers if k.lower() == b"strict-transport-security"]
        assert hsts
        # No includeSubDomains unless explicitly enabled.
        assert b"includeSubDomains" not in hsts[0]

    @pytest.mark.asyncio
    async def test_hsts_emitted_on_local_https_when_trusted(self, hardened_app) -> None:
        """If the local socket itself is https (production tunnel direct), HSTS is OK."""
        scope = _build_scope(
            path="/health",
            peer=("127.0.0.1", 51234),
            host_header="markee.batata.cc",
            scheme="https",
        )
        status, headers, _body = await _invoke(scope)
        assert status == 200
        hsts = [v for k, v in headers if k.lower() == b"strict-transport-security"]
        assert hsts


# ── Docs / OpenAPI gating ──────────────────────────────────────────────────


class TestDocsGating:
    """OpenAPI surfaces are development-only; production must hide them."""

    @pytest.mark.asyncio
    async def test_docs_404_in_production(self, hardened_app) -> None:
        scope = _build_scope(
            path="/docs",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 404

    @pytest.mark.asyncio
    async def test_redoc_404_in_production(self, hardened_app) -> None:
        scope = _build_scope(
            path="/redoc",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 404

    @pytest.mark.asyncio
    async def test_openapi_json_404_in_production(self, hardened_app) -> None:
        scope = _build_scope(
            path="/openapi.json",
            peer=("127.0.0.1", 51234),
            host_header="127.0.0.1:8000",
        )
        status, _headers, _body = await _invoke(scope)
        assert status == 404